import { inter } from '@/app/ui/fonts';
import './styles/globals.css';

export const metadata = {
  title: 'Create Your Own Advent Calendar',
  description: 'Generated by You!',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
